namespace PermuteMMO.Lib;

public static class PokemonLocationUtil
{
    // Yes this is pretty inefficient, but I don't want to work more with it than I have to
    public static Array Pokemon = new[]
    {
        new {Text = "Abomasnow", Value = "Abomasnow"},
        new {Text = "Abra", Value = "Abra"},
        new {Text = "Aipom", Value = "Aipom"},
        new {Text = "Ambipom", Value = "Ambipom"},
        new {Text = "Avalugg", Value = "Avalugg"},
        new {Text = "Barboach", Value = "Barboach"},
        new {Text = "Basculin", Value = "Basculin"},
        new {Text = "Beautifly", Value = "Beautifly"},
        new {Text = "Bergmite", Value = "Bergmite"},
        new {Text = "Bibarel", Value = "Bibarel"},
        new {Text = "Bidoof", Value = "Bidoof"},
        new {Text = "Bonsly", Value = "Bonsly"},
        new {Text = "Braviary", Value = "Braviary"},
        new {Text = "Bronzong", Value = "Bronzong"},
        new {Text = "Bronzor", Value = "Bronzor"},
        new {Text = "Budew", Value = "Budew"},
        new {Text = "Buizel", Value = "Buizel"},
        new {Text = "Buneary", Value = "Buneary"},
        new {Text = "Carnivine", Value = "Carnivine"},
        new {Text = "Cascoon", Value = "Cascoon"},
        new {Text = "Chansey", Value = "Chansey"},
        new {Text = "Chatot", Value = "Chatot"},
        new {Text = "Cherubi", Value = "Cherubi"},
        new {Text = "Chimchar", Value = "Chimchar"},
        new {Text = "Chimecho", Value = "Chimecho"},
        new {Text = "Chingling", Value = "Chingling"},
        new {Text = "Clefairy", Value = "Clefairy"},
        new {Text = "Cleffa", Value = "Cleffa"},
        new {Text = "Combee", Value = "Combee"},
        new {Text = "Croagunk", Value = "Croagunk"},
        new {Text = "Drapion", Value = "Drapion"},
        new {Text = "Drifblim", Value = "Drifblim"},
        new {Text = "Drifloon", Value = "Drifloon"},
        new {Text = "Dusclops", Value = "Dusclops"},
        new {Text = "Duskull", Value = "Duskull"},
        new {Text = "Dustox", Value = "Dustox"},
        new {Text = "Eevee", Value = "Eevee"},
        new {Text = "Electabuzz", Value = "Electabuzz"},
        new {Text = "Elekid", Value = "Elekid"},
        new {Text = "Finneon", Value = "Finneon"},
        new {Text = "Floatzel", Value = "Floatzel"},
        new {Text = "Gabite", Value = "Gabite"},
        new {Text = "Gardevoir", Value = "Gardevoir"},
        new {Text = "Gastly", Value = "Gastly"},
        new {Text = "Gastrodon", Value = "Gastrodon"},
        new {Text = "Geodude", Value = "Geodude"},
        new {Text = "Gible", Value = "Gible"},
        new {Text = "Glalie", Value = "Glalie"},
        new {Text = "Glameow", Value = "Glameow"},
        new {Text = "Gligar", Value = "Gligar"},
        new {Text = "Golbat", Value = "Golbat"},
        new {Text = "Golduck", Value = "Golduck"},
        new {Text = "Goomy", Value = "Goomy"},
        new {Text = "Graveler", Value = "Graveler"},
        new {Text = "Grotle", Value = "Grotle"},
        new {Text = "Growlithe", Value = "Growlithe"},
        new {Text = "Gyarados", Value = "Gyarados"},
        new {Text = "Happiny", Value = "Happiny"},
        new {Text = "Haunter", Value = "Haunter"},
        new {Text = "Heracross", Value = "Heracross"},
        new {Text = "Hippopotas", Value = "Hippopotas"},
        new {Text = "Hippowdon", Value = "Hippowdon"},
        new {Text = "Kadabra", Value = "Kadabra"},
        new {Text = "Kirlia", Value = "Kirlia"},
        new {Text = "Kricketot", Value = "Kricketot"},
        new {Text = "Kricketune", Value = "Kricketune"},
        new {Text = "Lickilicky", Value = "Lickilicky"},
        new {Text = "Lickitung", Value = "Lickitung"},
        new {Text = "Lumineon", Value = "Lumineon"},
        new {Text = "Luxio", Value = "Luxio"},
        new {Text = "Luxray", Value = "Luxray"},
        new {Text = "Machoke", Value = "Machoke"},
        new {Text = "Machop", Value = "Machop"},
        new {Text = "Magby", Value = "Magby"},
        new {Text = "Magikarp", Value = "Magikarp"},
        new {Text = "Magmar", Value = "Magmar"},
        new {Text = "Mamoswine", Value = "Mamoswine"},
        new {Text = "Mantine", Value = "Mantine"},
        new {Text = "Mantyke", Value = "Mantyke"},
        new {Text = "Mime Jr.", Value = "MimeJr"},
        new {Text = "Misdreavus", Value = "Misdreavus"},
        new {Text = "Monferno", Value = "Monferno"},
        new {Text = "Mr. Mime", Value = "MrMime"},
        new {Text = "Munchlax", Value = "Munchlax"},
        new {Text = "Murkrow", Value = "Murkrow"},
        new {Text = "Nosepass", Value = "Nosepass"},
        new {Text = "Octillery", Value = "Octillery"},
        new {Text = "Onix", Value = "Onix"},
        new {Text = "Pachirisu", Value = "Pachirisu"},
        new {Text = "Paras", Value = "Paras"},
        new {Text = "Parasect", Value = "Parasect"},
        new {Text = "Petilil", Value = "Petilil"},
        new {Text = "Pichu", Value = "Pichu"},
        new {Text = "Pikachu", Value = "Pikachu"},
        new {Text = "Piloswine", Value = "Piloswine"},
        new {Text = "Piplup", Value = "Piplup"},
        new {Text = "Ponyta", Value = "Ponyta"},
        new {Text = "Prinplup", Value = "Prinplup"},
        new {Text = "Psyduck", Value = "Psyduck"},
        new {Text = "Purugly", Value = "Purugly"},
        new {Text = "Qwilfish", Value = "Qwilfish"},
        new {Text = "Ralts", Value = "Ralts"},
        new {Text = "Rapidash", Value = "Rapidash"},
        new {Text = "Remoraid", Value = "Remoraid"},
        new {Text = "Rhydon", Value = "Rhydon"},
        new {Text = "Rhyhorn", Value = "Rhyhorn"},
        new {Text = "Riolu", Value = "Riolu"},
        new {Text = "Roselia", Value = "Roselia"},
        new {Text = "Rotom", Value = "Rotom"},
        new {Text = "Rufflet", Value = "Rufflet"},
        new {Text = "Scyther", Value = "Scyther"},
        new {Text = "Sealeo", Value = "Sealeo"},
        new {Text = "Shellos", Value = "Shellos"},
        new {Text = "Shinx", Value = "Shinx"},
        new {Text = "Silcoon", Value = "Silcoon"},
        new {Text = "Skorupi", Value = "Skorupi"},
        new {Text = "Skuntank", Value = "Skuntank"},
        new {Text = "Sliggoo", Value = "Sliggoo"},
        new {Text = "Sneasel", Value = "Sneasel"},
        new {Text = "Snorunt", Value = "Snorunt"},
        new {Text = "Snover", Value = "Snover"},
        new {Text = "Spheal", Value = "Spheal"},
        new {Text = "Stantler", Value = "Stantler"},
        new {Text = "Staraptor", Value = "Staraptor"},
        new {Text = "Staravia", Value = "Staravia"},
        new {Text = "Starly", Value = "Starly"},
        new {Text = "Stunky", Value = "Stunky"},
        new {Text = "Sudowoodo", Value = "Sudowoodo"},
        new {Text = "Swinub", Value = "Swinub"},
        new {Text = "Tangela", Value = "Tangela"},
        new {Text = "Tangrowth", Value = "Tangrowth"},
        new {Text = "Teddiursa", Value = "Teddiursa"},
        new {Text = "Tentacool", Value = "Tentacool"},
        new {Text = "Tentacruel", Value = "Tentacruel"},
        new {Text = "Togepi", Value = "Togepi"},
        new {Text = "Toxicroak", Value = "Toxicroak"},
        new {Text = "Turtwig", Value = "Turtwig"},
        new {Text = "Ursaring", Value = "Ursaring"},
        new {Text = "Voltorb", Value = "Voltorb"},
        new {Text = "Vulpix", Value = "Vulpix"},
        new {Text = "Walrein", Value = "Walrein"},
        new {Text = "Whiscash", Value = "Whiscash"},
        new {Text = "Wurmple", Value = "Wurmple"},
        new {Text = "Yanma", Value = "Yanma"},
        new {Text = "Yanmega", Value = "Yanmega"},
        new {Text = "Zoroark", Value = "Zoroark"},
        new {Text = "Zorua", Value = "Zorua"},
        new {Text = "Zubat", Value = "Zubat"}
    };

    public static Array ObsidianFieldlandsAPokemon = new[]
    {
        new{Text = "Abra",Value = "Abra"},
        new{Text = "Bidoof",Value = "Bidoof"},
        new{Text = "Buizel",Value = "Buizel"},
        new{Text = "Buneary",Value = "Buneary"},
        new{Text = "Cascoon",Value = "Cascoon"},
        new{Text = "Chatot",Value = "Chatot"},
        new{Text = "Chimchar",Value = "Chimchar"},
        new{Text = "Drifloon",Value = "Drifloon"},
        new{Text = "Geodude",Value = "Geodude"},
        new{Text = "Golbat",Value = "Golbat"},
        new{Text = "Graveler",Value = "Graveler"},
        new{Text = "Kadabra",Value = "Kadabra"},
        new{Text = "Kricketot",Value = "Kricketot"},
        new{Text = "Luxio",Value = "Luxio"},
        new{Text = "Mime Jr.",Value = "MimeJr"},
        new{Text = "Monferno",Value = "Monferno"},
        new{Text = "Munchlax",Value = "Munchlax"},
        new{Text = "Paras",Value = "Paras"},
        new{Text = "Pichu",Value = "Pichu"},
        new{Text = "Pikachu",Value = "Pikachu"},
        new{Text = "Ponyta",Value = "Ponyta"},
        new{Text = "Scyther",Value = "Scyther"},
        new{Text = "Shellos (Pink)",Value = "Shellos"},
        new{Text = "Shinx",Value = "Shinx"},
        new{Text = "Silcoon",Value = "Silcoon"},
        new{Text = "Spheal",Value = "Spheal"},
        new{Text = "Stantler",Value = "Stantler"},
        new{Text = "Staravia",Value = "Staravia"},
        new{Text = "Starly",Value = "Starly"},
        new{Text = "Wurmple (+Cascoon)",Value = "Wurmple"},
        new{Text = "Wurmple (+Silcoon)",Value = "Wurmple"},
        new{Text = "Zorua",Value = "Zorua"},
        new{Text = "Zubat",Value = "Zubat"},
    };

    public static Array ObsidianFieldlandsBPokemon = new[]
    {
        new {Text = "Alakazam", Value = "Alakazam"},
        new {Text = "Beautifly", Value = "Beautifly"},
        new {Text = "Bibarel", Value = "Bibarel"},
        new {Text = "Cascoon", Value = "Cascoon"},
        new {Text = "Crobat", Value = "Crobat"},
        new {Text = "Drifblim", Value = "Drifblim"},
        new {Text = "Dustox", Value = "Dustox"},
        new {Text = "Floatzel", Value = "Floatzel"},
        new {Text = "Gastrodon (Pink)", Value = "Gastrodon"},
        new {Text = "Golbat", Value = "Golbat"},
        new {Text = "Golem", Value = "Golem"},
        new {Text = "Graveler", Value = "Graveler"},
        new {Text = "Infernape", Value = "Infernape"},
        new {Text = "Kadabra", Value = "Kadabra"},
        new {Text = "Kleavor", Value = "Kleavor"},
        new {Text = "Kricketune", Value = "Kricketune"},
        new {Text = "Lopunny", Value = "Lopunny"},
        new {Text = "Luxio", Value = "Luxio"},
        new {Text = "Luxray", Value = "Luxray"},
        new {Text = "Monferno", Value = "Monferno"},
        new {Text = "Mr. Mime", Value = "MrMime"},
        new {Text = "Parasect", Value = "Parasect"},
        new {Text = "Pikachu", Value = "Pikachu"},
        new {Text = "Raichu", Value = "Raichu"},
        new {Text = "Rapidash", Value = "Rapidash"},
        new {Text = "Sealeo", Value = "Sealeo"},
        new {Text = "Silcoon", Value = "Silcoon"},
        new {Text = "Snorlax", Value = "Snorlax"},
        new {Text = "Staraptor", Value = "Staraptor"},
        new {Text = "Staravia", Value = "Staravia"},
        new {Text = "Wyrdeer", Value = "Wyrdeer"},
        new {Text = "Zoroark", Value = "Zoroark"},

    };

    public static Array CrimsonMirelandsAPokemon = new[]
    {
        new {Text = "Bonsly", Value = "Bonsly"},
        new {Text = "Bronzor", Value = "Bronzor"},
        new {Text = "Budew", Value = "Budew"},
        new {Text = "Carnivine", Value = "Carnivine"},
        new {Text = "Croagunk", Value = "Croagunk"},
        new {Text = "Cyndaquil", Value = "Cyndaquil"},
        new {Text = "Gastly", Value = "Gastly"},
        new {Text = "Goomy", Value = "Goomy"},
        new {Text = "Grotle", Value = "Grotle"},
        new {Text = "Haunter", Value = "Haunter"},
        new {Text = "Hippopotas", Value = "Hippopotas"},
        new {Text = "Kricketot", Value = "Kricketot"},
        new {Text = "Lickitung", Value = "Lickitung"},
        new {Text = "Murkrow", Value = "Murkrow"},
        new {Text = "Onix", Value = "Onix"},
        new {Text = "Pachirisu", Value = "Pachirisu"},
        new {Text = "Paras", Value = "Paras"},
        new {Text = "Petilil", Value = "Petilil"},
        new {Text = "Psyduck", Value = "Psyduck"},
        new {Text = "Quilava", Value = "Quilava"},
        new {Text = "Rhydon", Value = "Rhydon"},
        new {Text = "Rhyhorn", Value = "Rhyhorn"},
        new {Text = "Roselia", Value = "Roselia"},
        new {Text = "Skorupi", Value = "Skorupi"},
        new {Text = "Sliggoo", Value = "Sliggoo"},
        new {Text = "Spiritomb", Value = "Spiritomb"},
        new {Text = "Stunky", Value = "Stunky"},
        new {Text = "Swinub", Value = "Swinub"},
        new {Text = "Tangela", Value = "Tangela"},
        new {Text = "Teddiursa", Value = "Teddiursa"},
        new {Text = "Turtwig", Value = "Turtwig"},
        new {Text = "Unown", Value = "Unown"},
        new {Text = "Ursaring", Value = "Ursaring"},
    };

    public static Array CrimsonMirelandsBPokemon = new[]
    {
        new {Text = "Bronzong", Value = "Bronzong"},
        new {Text = "Drapion", Value = "Drapion"},
        new {Text = "Gengar", Value = "Gengar"},
        new {Text = "Golduck", Value = "Golduck"},
        new {Text = "Goodra", Value = "Goodra"},
        new {Text = "Grotle", Value = "Grotle"},
        new {Text = "Haunter", Value = "Haunter"},
        new {Text = "Hippowdon", Value = "Hippowdon"},
        new {Text = "Honchkrow", Value = "Honchkrow"},
        new {Text = "Kricketune", Value = "Kricketune"},
        new {Text = "Lickilicky", Value = "Lickilicky"},
        new {Text = "Lilligant", Value = "Lilligant"},
        new {Text = "Parasect", Value = "Parasect"},
        new {Text = "Piloswine", Value = "Piloswine"},
        new {Text = "Quilava", Value = "Quilava"},
        new {Text = "Rhydon", Value = "Rhydon"},
        new {Text = "Rhyperior", Value = "Rhyperior"},
        new {Text = "Roselia", Value = "Roselia"},
        new {Text = "Roserade", Value = "Roserade"},
        new {Text = "Skuntank", Value = "Skuntank"},
        new {Text = "Sliggoo", Value = "Sliggoo"},
        new {Text = "Steelix", Value = "Steelix"},
        new {Text = "Sudowoodo", Value = "Sudowoodo"},
        new {Text = "Tangrowth", Value = "Tangrowth"},
        new {Text = "Torterra", Value = "Torterra"},
        new {Text = "Toxicroak", Value = "Toxicroak"},
        new {Text = "Typhlosion", Value = "Typhlosion"},
        new {Text = "Ursaluna", Value = "Ursaluna"},
        new {Text = "Ursaring", Value = "Ursaring"},
        new {Text = "Yanmega", Value = "Yanmega"},
    };

    public static Array CobaltCoastlandsAPokemon = new[]
    {
        new{Text = "Aipom",Value = "Aipom"},
        new{Text = "Basculin",Value = "Basculin"},
        new{Text = "Chansey",Value = "Chansey"},
        new{Text = "Chatot",Value = "Chatot"},
        new{Text = "Cleffa",Value = "Cleffa"},
        new{Text = "Finneon",Value = "Finneon"},
        new{Text = "Geodude",Value = "Geodude"},
        new{Text = "Glameow",Value = "Glameow"},
        new{Text = "Graveler",Value = "Graveler"},
        new{Text = "Growlithe",Value = "Growlithe"},
        new{Text = "Happiny",Value = "Happiny"},
        new{Text = "Machoke",Value = "Machoke"},
        new{Text = "Machop",Value = "Machop"},
        new{Text = "Magby",Value = "Magby"},
        new{Text = "Magikarp",Value = "Magikarp"},
        new{Text = "Magmar",Value = "Magmar"},
        new{Text = "Mantyke",Value = "Mantyke"},
        new{Text = "Onix",Value = "Onix"},
        new{Text = "Piplup",Value = "Piplup"},
        new{Text = "Prinplup",Value = "Prinplup"},
        new{Text = "Psyduck",Value = "Psyduck"},
        new{Text = "Qwilfish",Value = "Qwilfish"},
        new{Text = "Riolu",Value = "Riolu"},
        new{Text = "Sealeo",Value = "Sealeo"},
        new{Text = "Shellos (Blue)",Value = "Shellos"},
        new{Text = "Skorupi",Value = "Skorupi"},
        new{Text = "Spheal",Value = "Spheal"},
        new{Text = "Staravia",Value = "Staravia"},
        new{Text = "Starly",Value = "Starly"},
        new{Text = "Tentacool",Value = "Tentacool"},
        new{Text = "Togepi",Value = "Togepi"},
        new{Text = "Togetic",Value = "Togetic"},
        new{Text = "Vulpix",Value = "Vulpix"},

    };

    public static Array CobaltCoastlandsBPokemon = new[]
    {
        new {Text = "Ambipom", Value = "Ambipom"},
        new {Text = "Arcanine", Value = "Arcanine"},
        new {Text = "Basculegion", Value = "Basculegion"},
        new {Text = "Blissey", Value = "Blissey"},
        new {Text = "Chansey", Value = "Chansey"},
        new {Text = "Clefairy", Value = "Clefairy"},
        new {Text = "Drapion", Value = "Drapion"},
        new {Text = "Empoleon", Value = "Empoleon"},
        new {Text = "Gastrodon (Blue)", Value = "Gastrodon"},
        new {Text = "Golduck", Value = "Golduck"},
        new {Text = "Golem", Value = "Golem"},
        new {Text = "Graveler", Value = "Graveler"},
        new {Text = "Gyarados", Value = "Gyarados"},
        new {Text = "Lucario", Value = "Lucario"},
        new {Text = "Lumineon", Value = "Lumineon"},
        new {Text = "Machamp", Value = "Machamp"},
        new {Text = "Machoke", Value = "Machoke"},
        new {Text = "Magmar", Value = "Magmar"},
        new {Text = "Magmortar", Value = "Magmortar"},
        new {Text = "Mantine", Value = "Mantine"},
        new {Text = "Ninetales", Value = "Ninetales"},
        new {Text = "Overqwil", Value = "Overqwil"},
        new {Text = "Prinplup", Value = "Prinplup"},
        new {Text = "Purugly", Value = "Purugly"},
        new {Text = "Sealeo", Value = "Sealeo"},
        new {Text = "Staraptor", Value = "Staraptor"},
        new {Text = "Staravia", Value = "Staravia"},
        new {Text = "Steelix", Value = "Steelix"},
        new {Text = "Tentacruel", Value = "Tentacruel"},
        new {Text = "Togekiss", Value = "Togekiss"},
        new {Text = "Togetic", Value = "Togetic"},
        new {Text = "Walrein", Value = "Walrein"},

    };

    public static Array CoronetHighlandsAPokemon = new[]
    {
        new {Text = "Bronzor", Value = "Bronzor"},
        new {Text = "Chingling", Value = "Chingling"},
        new {Text = "Clefairy", Value = "Clefairy"},
        new {Text = "Cleffa", Value = "Cleffa"},
        new {Text = "Dartrix", Value = "Dartrix"},
        new {Text = "Dusclops", Value = "Dusclops"},
        new {Text = "Duskull", Value = "Duskull"},
        new {Text = "Electabuzz", Value = "Electabuzz"},
        new {Text = "Elekid", Value = "Elekid"},
        new {Text = "Gabite", Value = "Gabite"},
        new {Text = "Gastly", Value = "Gastly"},
        new {Text = "Geodude", Value = "Geodude"},
        new {Text = "Gible", Value = "Gible"},
        new {Text = "Gligar", Value = "Gligar"},
        new {Text = "Graveler", Value = "Graveler"},
        new {Text = "Haunter", Value = "Haunter"},
        new {Text = "Heracross", Value = "Heracross"},
        new {Text = "Hippopotas", Value = "Hippopotas"},
        new {Text = "Luxio", Value = "Luxio"},
        new {Text = "Mime Jr.", Value = "MimeJr"},
        new {Text = "Misdreavus", Value = "Misdreavus"},
        new {Text = "Nosepass", Value = "Nosepass"},
        new {Text = "Ponyta", Value = "Ponyta"},
        new {Text = "Rhydon", Value = "Rhydon"},
        new {Text = "Rhyhorn", Value = "Rhyhorn"},
        new {Text = "Rotom", Value = "Rotom"},
        new {Text = "Rowlet", Value = "Rowlet"},
        new {Text = "Shinx", Value = "Shinx"},
        new {Text = "Sneasel", Value = "Sneasel"},
        new {Text = "Snover", Value = "Snover"},
        new {Text = "Stunky", Value = "Stunky"},
        new {Text = "Voltorb", Value = "Voltorb"},
        new {Text = "Yanma", Value = "Yanma"},

    };

    public static Array CoronetHighlandsBPokemon = new[]
    {
        new {Text = "Abomasnow", Value = "Abomasnow"},
        new {Text = "Bronzong", Value = "Bronzong"},
        new {Text = "Chimecho", Value = "Chimecho"},
        new {Text = "Clefable", Value = "Clefable"},
        new {Text = "Clefairy", Value = "Clefairy"},
        new {Text = "Dartrix", Value = "Dartrix"},
        new {Text = "Decidueye", Value = "Decidueye"},
        new {Text = "Dusclops", Value = "Dusclops"},
        new {Text = "Dusknoir", Value = "Dusknoir"},
        new {Text = "Electabuzz", Value = "Electabuzz"},
        new {Text = "Electivire", Value = "Electivire"},
        new {Text = "Electrode", Value = "Electrode"},
        new {Text = "Gabite", Value = "Gabite"},
        new {Text = "Garchomp", Value = "Garchomp"},
        new {Text = "Gengar", Value = "Gengar"},
        new {Text = "Gliscor", Value = "Gliscor"},
        new {Text = "Golem", Value = "Golem"},
        new {Text = "Graveler", Value = "Graveler"},
        new {Text = "Haunter", Value = "Haunter"},
        new {Text = "Hippowdon", Value = "Hippowdon"},
        new {Text = "Luxio", Value = "Luxio"},
        new {Text = "Luxray", Value = "Luxray"},
        new {Text = "Mismagius", Value = "Mismagius"},
        new {Text = "Mr. Mime", Value = "MrMime"},
        new {Text = "Probopass", Value = "Probopass"},
        new {Text = "Rapidash", Value = "Rapidash"},
        new {Text = "Rhydon", Value = "Rhydon"},
        new {Text = "Rhyperior", Value = "Rhyperior"},
        new {Text = "Skuntank", Value = "Skuntank"},
        new {Text = "Sneasler", Value = "Sneasler"},
        new {Text = "Yanmega", Value = "Yanmega"},
    };

    public static Array AlabasterIcelandsAPokemon = new[]
    {
        new {Text = "Abra", Value = "Abra"},
        new {Text = "Aipom", Value = "Aipom"},
        new {Text = "Bergmite", Value = "Bergmite"},
        new {Text = "Bidoof", Value = "Bidoof"},
        new {Text = "Bronzor", Value = "Bronzor"},
        new {Text = "Buneary", Value = "Buneary"},
        new {Text = "Dewott", Value = "Dewott"},
        new {Text = "Drifloon", Value = "Drifloon"},
        new {Text = "Dusclops", Value = "Dusclops"},
        new {Text = "Duskull", Value = "Duskull"},
        new {Text = "Gastly", Value = "Gastly"},
        new {Text = "Glameow", Value = "Glameow"},
        new {Text = "Haunter", Value = "Haunter"},
        new {Text = "Kadabra", Value = "Kadabra"},
        new {Text = "Kirlia (+Gallade)", Value = "Kirlia"},
        new {Text = "Kirlia (+Gardevoir)", Value = "Kirlia"},
        new {Text = "Lickitung", Value = "Lickitung"},
        new {Text = "Machoke", Value = "Machoke"},
        new {Text = "Machop", Value = "Machop"},
        new {Text = "Magby", Value = "Magby"},
        new {Text = "Misdreavus", Value = "Misdreavus"},
        new {Text = "Oshawott", Value = "Oshawott"},
        new {Text = "Pachirisu", Value = "Pachirisu"},
        new {Text = "Piloswine", Value = "Piloswine"},
        new {Text = "Ralts", Value = "Ralts"},
        new {Text = "Riolu", Value = "Riolu"},
        new {Text = "Rufflet", Value = "Rufflet"},
        new {Text = "Snorunt (+Froslass)", Value = "Snorunt"},
        new {Text = "Snorunt (+Glalie)", Value = "Snorunt"},
        new {Text = "Snover", Value = "Snover"},
        new {Text = "Swinub", Value = "Swinub"},
        new {Text = "Vulpix", Value = "Vulpix"},
        new {Text = "Zorua", Value = "Zorua"},

    };

    public static Array AlabasterIcelandsBPokemon = new[]
    {
        new {Text = "Abomasnow", Value = "Abomasnow"},
        new {Text = "Alakazam", Value = "Alakazam"},
        new {Text = "Ambipom", Value = "Ambipom"},
        new {Text = "Avalugg", Value = "Avalugg"},
        new {Text = "Bibarel", Value = "Bibarel"},
        new {Text = "Braviary", Value = "Braviary"},
        new {Text = "Bronzong", Value = "Bronzong"},
        new {Text = "Dewott", Value = "Dewott"},
        new {Text = "Drifblim", Value = "Drifblim"},
        new {Text = "Dusclops", Value = "Dusclops"},
        new {Text = "Dusknoir", Value = "Dusknoir"},
        new {Text = "Froslass", Value = "Froslass"},
        new {Text = "Gallade", Value = "Gallade"},
        new {Text = "Gardevoir", Value = "Gardevoir"},
        new {Text = "Gengar", Value = "Gengar"},
        new {Text = "Glalie", Value = "Glalie"},
        new {Text = "Haunter", Value = "Haunter"},
        new {Text = "Kadabra", Value = "Kadabra"},
        new {Text = "Kirlia", Value = "Kirlia"},
        new {Text = "Lickilicky", Value = "Lickilicky"},
        new {Text = "Lopunny", Value = "Lopunny"},
        new {Text = "Lucario", Value = "Lucario"},
        new {Text = "Machamp", Value = "Machamp"},
        new {Text = "Machoke", Value = "Machoke"},
        new {Text = "Magmar", Value = "Magmar"},
        new {Text = "Mamoswine", Value = "Mamoswine"},
        new {Text = "Mismagius", Value = "Mismagius"},
        new {Text = "Ninetales", Value = "Ninetales"},
        new {Text = "Piloswine", Value = "Piloswine"},
        new {Text = "Purugly", Value = "Purugly"},
        new {Text = "Samurott", Value = "Samurott"},
        new {Text = "Zoroark", Value = "Zoroark"},
    };
}
